#!/bin/sh
set -ex
export PERL_TEST_HARNET_DUMP_TAP=./logs
export TEST_VERBOSE=1

[ -f Makefile ] && make realclean
rm -rf Makefile Makfile.old MANIFEST blib *.tar.gz
[ -d logs ] && rm -rf logs/
[ -f checkstyle-result.xml ] && rm -f checkstyle-result.xml
[ -d cover_db ] && carton exec -Ilib -- cover -delete

mkdir logs/

HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,local \
carton exec -Ilib -- prove -vl --timer --formatter TAP::Formatter::JUnit \
    t/ | grep -v ^Devel::Cover > logs/tests.xml
carton exec -Ilib -- cover -report clover
carton exec -Ilib -- cover
carton exec -Ilib -- measureperl-checkstyle --max_sub_lines 60 --max_sub_mccabe_complexity 13 --directory lib > checkstyle-result.xml
